//
// Created by wortelus on 22.11.21.
//

#ifndef TETRIS_CONSTANTS_H
#define TETRIS_CONSTANTS_H

#include "time.h"

typedef struct Point {
    int W, H;
} Point;

static const int PLAY_BLOCK_WIDTH = 10;
static const int PLAY_BLOCK_HEIGHT = 20;
static const int PLAY_BLOCK_COUNT = PLAY_BLOCK_WIDTH * PLAY_BLOCK_HEIGHT;

static const int SIDEBAR_BLOCK_WIDTH = 6;
static const int SIDEBAR_BLOCK_HEIGHT = PLAY_BLOCK_HEIGHT;

static const int BLOCK_SIZE = 32;
static const int BLOCK_GAP_SIZE = 4;

static const int PLAY_TOTAL_WIDTH = (PLAY_BLOCK_WIDTH * BLOCK_SIZE) + (PLAY_BLOCK_WIDTH - 1) * BLOCK_GAP_SIZE;
static const int SIDEBAR_TOTAL_WIDTH = (SIDEBAR_BLOCK_WIDTH * BLOCK_SIZE) + (SIDEBAR_BLOCK_WIDTH - 1) * BLOCK_GAP_SIZE;
static const int TOTAL_WIDTH = PLAY_TOTAL_WIDTH + SIDEBAR_TOTAL_WIDTH + BLOCK_GAP_SIZE;

static const int PLAY_TOTAL_HEIGHT = (PLAY_BLOCK_HEIGHT * BLOCK_SIZE) + (PLAY_BLOCK_HEIGHT - 1) * BLOCK_GAP_SIZE;
static const int SIDEBAR_TOTAL_HEIGHT = PLAY_TOTAL_HEIGHT;
static const int TOTAL_HEIGHT = PLAY_TOTAL_HEIGHT;

static const int PLAY_NEXT_ACTIVE_BLOCK_POSITION_X = PLAY_TOTAL_WIDTH + (BLOCK_SIZE + BLOCK_GAP_SIZE) * 1;
static const int PLAY_NEXT_ACTIVE_BLOCK_POSITION_Y = (BLOCK_SIZE + BLOCK_GAP_SIZE) * 4;

static const int PLAY_NEXT_ACTIVE_BLOCK_LABEL_X = PLAY_NEXT_ACTIVE_BLOCK_POSITION_X;
static const int PLAY_NEXT_ACTIVE_BLOCK_LABEL_Y = PLAY_NEXT_ACTIVE_BLOCK_POSITION_Y - (BLOCK_SIZE + BLOCK_GAP_SIZE);

static const int SCORE_LABEL_X = PLAY_NEXT_ACTIVE_BLOCK_POSITION_X;
static const int SCORE_LABEL_Y = (BLOCK_SIZE + BLOCK_GAP_SIZE) * 1;

static const int YOU_LOST_LABEL_X = PLAY_NEXT_ACTIVE_BLOCK_POSITION_X;
static const int YOU_LOST_LABEL_Y = (BLOCK_SIZE + BLOCK_GAP_SIZE) * 6;

static const double SECONDS_SLEEP = 0.5;
static const int MILLISECONDS_LR_PERIOD_SLEEP = 10;

static const int PATTERN_COUNT = 7;

#endif //TETRIS_CONSTANTS_H
